services:
  redis:
    image: redis
    ports: 
      - "6379:6379"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ai_image
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "3232:80"
    depends_on:
      - postgres
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    
volumes:
  postgres_data:
  pgadmin_data:    
